apiVersion: plural.sh/v1alpha1
kind: Dependencies
metadata:
  description: minio kind setup
  version: 0.1.0
spec:
  dependencies:
  - name: kind-bootstrap
    repo: bootstrap
    type: terraform
    version: '>= 0.1.0'
  providers:
  - kind
